<?php

namespace EntitiesBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function findDQL($id)
    {
        $dqlresult = $this->getEntityManager()
            ->createQuery("SELECT c
                               FROM 
                                    EntitiesBundle:Comment c
                               WHERE
                                    c.post = '$id'
                                  
                              ");
        return $dqlresult->getResult();
    }

}
