<?php

namespace EntitiesBundle\Repository;

/**
 * MetapostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MetapostRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $id
     * @return array
     */
    public function findMetaDQL($id)
    {
        $dqlresult = $this->getEntityManager()
            ->createQuery("SELECT c
                               FROM 
                                    EntitiesBundle:Metapost c
                               WHERE
                                    c.post = '$id'
                                    
                              ");
        return $dqlresult->getResult();
    }
    public function findMulti($find)
    {
        $q=$this->createQueryBuilder('m')
            ->where('m.titre LIKE :find')
            ->setParameter(':find',"%$find%");
        return $q->getQuery()->getResult();
    }
}
