<?php

namespace EntitiesBundle\Repository;

/**
 * MetacommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MetacommentRepository extends \Doctrine\ORM\EntityRepository
{
}
