wiem:
    resource: "@WiemBundle/Resources/config/routing.yml"
    prefix:   /Team_req

projects:
    resource: "@ProjectsBundle/Resources/config/routing.yml"
    prefix:   /projet

bp:
    resource: "@BPBundle/Resources/config/routing.yml"
    prefix:   /bp

bs:
    resource: "@BSBundle/Resources/config/routing.yml"
    prefix:   /bs

rh:
    resource: "@RhBundle/Resources/config/routing.yml"
    prefix:   /rh

forum:
    resource: "@ForumBundle/Resources/config/routing.yml"
    prefix:   /Forum

meeting:
    resource: "@MeetingBundle/Resources/config/routing.yml"
    prefix:   /Meeting



fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /msg

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register


fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

entities:
    resource: "@EntitiesBundle/Resources/config/routing.yml"
    prefix:   /entities



app:
    resource: '@AppBundle/Controller/'
    prefix:   /
